version: '3.4'

services:
  worldofgamecraft.accountservice.api:
    image: ${DOCKER_REGISTRY-}worldofgamecraftaccountserviceapi
    container_name: Gamecraft.Account
    build:
      context: .
      dockerfile: WorldOfGamecraft.AccountService.Api/Dockerfile
    ports:
      - 8888:8080
      - 8881:8081
    depends_on:
      - gamecraft-db

  gamecraft-db:
    image: postgres:latest
    container_name: Gamecraft.Db
    environment:
      - POSTGRES_DB=gamecraft-identity
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
