// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldOfGamecraft.CharacterService.Infrastructure;

#nullable disable

namespace WorldOfGamecraft.CharacterService.Infrastructure.Migrations
{
    [DbContext(typeof(CharactersDbContext))]
    [Migration("20240413144120_AddedCreatedByColumn")]
    partial class AddedCreatedByColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.CharacterClasses.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_name");

                    b.ToTable("classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("89ecac8e-a182-4d0c-a428-5e95367f7a77"),
                            Description = "Est et amet aut illum nisi.",
                            Name = "Warrior"
                        },
                        new
                        {
                            Id = new Guid("83454a3b-ada5-4580-8ec8-aac5ec1e6a8e"),
                            Description = "Ea exercitationem dolore alias in a commodi.",
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = new Guid("9547a77e-6af5-47a1-a294-ed29e99f554a"),
                            Description = "Earum molestiae cupiditate.",
                            Name = "Mage"
                        },
                        new
                        {
                            Id = new Guid("8f15218c-eb7a-44b0-9580-e610ff6f6ca1"),
                            Description = "Ullam ut in molestias deleniti ut a.",
                            Name = "Priest"
                        },
                        new
                        {
                            Id = new Guid("15dc6b97-75ec-494f-8626-95ee15179df8"),
                            Description = "Fugiat quia voluptas dolorum dignissimos.",
                            Name = "Elf"
                        },
                        new
                        {
                            Id = new Guid("e828e22e-9e02-467d-8daf-9c21881bce09"),
                            Description = "Aspernatur labore soluta sunt voluptate modi sunt voluptates qui praesentium.",
                            Name = "Necromancer"
                        });
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseAgility")
                        .HasColumnType("integer")
                        .HasColumnName("base_agility");

                    b.Property<int>("BaseFaith")
                        .HasColumnType("integer")
                        .HasColumnName("base_faith");

                    b.Property<int>("BaseIntelligence")
                        .HasColumnType("integer")
                        .HasColumnName("base_intelligence");

                    b.Property<int>("BaseStrength")
                        .HasColumnType("integer")
                        .HasColumnName("base_strength");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<int>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_characters_class_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_name");

                    b.ToTable("characters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("808603ad-738a-4fa0-83c5-299456c77ba7"),
                            BaseAgility = 29,
                            BaseFaith = 36,
                            BaseIntelligence = 21,
                            BaseStrength = 47,
                            ClassId = new Guid("8f15218c-eb7a-44b0-9580-e610ff6f6ca1"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Health = 1057,
                            Mana = 167,
                            Name = "AdonisTheInternational Division Designer"
                        },
                        new
                        {
                            Id = new Guid("42c8ee48-5939-48cb-82cd-d53fb02d5167"),
                            BaseAgility = 39,
                            BaseFaith = 47,
                            BaseIntelligence = 36,
                            BaseStrength = 17,
                            ClassId = new Guid("15dc6b97-75ec-494f-8626-95ee15179df8"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Health = 917,
                            Mana = 240,
                            Name = "LeeTheSenior Configuration Director"
                        },
                        new
                        {
                            Id = new Guid("308dc115-c571-4646-b044-51288e30886e"),
                            BaseAgility = 27,
                            BaseFaith = 33,
                            BaseIntelligence = 31,
                            BaseStrength = 15,
                            ClassId = new Guid("15dc6b97-75ec-494f-8626-95ee15179df8"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Health = 813,
                            Mana = 250,
                            Name = "RashadTheInternal Intranet Representative"
                        },
                        new
                        {
                            Id = new Guid("7bf3c011-f32b-4d1e-af4e-148ea55812ee"),
                            BaseAgility = 42,
                            BaseFaith = 50,
                            BaseIntelligence = 47,
                            BaseStrength = 39,
                            ClassId = new Guid("e828e22e-9e02-467d-8daf-9c21881bce09"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Health = 863,
                            Mana = 365,
                            Name = "AdamTheHuman Solutions Planner"
                        },
                        new
                        {
                            Id = new Guid("aa1646cf-6605-4a78-bc60-26a3011a71fe"),
                            BaseAgility = 38,
                            BaseFaith = 33,
                            BaseIntelligence = 24,
                            BaseStrength = 50,
                            ClassId = new Guid("9547a77e-6af5-47a1-a294-ed29e99f554a"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Health = 1283,
                            Mana = 496,
                            Name = "GiuseppeTheFuture Paradigm Strategist"
                        });
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BonusAgility")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_agility");

                    b.Property<int>("BonusFaith")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_faith");

                    b.Property<int>("BonusIntelligence")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_intelligence");

                    b.Property<int>("BonusStrength")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_strength");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_items_character_id");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2102983-3437-429c-aa7a-0aab66eefdf5"),
                            BonusAgility = 21,
                            BonusFaith = 21,
                            BonusIntelligence = 37,
                            BonusStrength = 12,
                            CharacterId = new Guid("808603ad-738a-4fa0-83c5-299456c77ba7"),
                            Description = "Et cum placeat eum sit sint molestias voluptas.",
                            Name = "heart"
                        },
                        new
                        {
                            Id = new Guid("946efaa8-55ac-4f23-b49b-071148cb7bde"),
                            BonusAgility = 24,
                            BonusFaith = 13,
                            BonusIntelligence = 45,
                            BonusStrength = 22,
                            CharacterId = new Guid("42c8ee48-5939-48cb-82cd-d53fb02d5167"),
                            Description = "Facere expedita ipsum consequuntur dolor laborum veritatis.",
                            Name = "orchid"
                        },
                        new
                        {
                            Id = new Guid("dacdc435-9c15-44f5-af27-8f744ee4acde"),
                            BonusAgility = 49,
                            BonusFaith = 35,
                            BonusIntelligence = 28,
                            BonusStrength = 21,
                            CharacterId = new Guid("308dc115-c571-4646-b044-51288e30886e"),
                            Description = "Voluptatibus aut inventore et beatae ut dolorum earum beatae hic.",
                            Name = "monkey_king_bar"
                        },
                        new
                        {
                            Id = new Guid("1574d992-e2ec-4adb-8d4a-3a63628b77fd"),
                            BonusAgility = 40,
                            BonusFaith = 20,
                            BonusIntelligence = 32,
                            BonusStrength = 31,
                            CharacterId = new Guid("7bf3c011-f32b-4d1e-af4e-148ea55812ee"),
                            Description = "Atque quos expedita omnis voluptatum quos odit sed quae modi.",
                            Name = "refresher"
                        },
                        new
                        {
                            Id = new Guid("2625112f-fd45-4bd5-a6d0-a03951ea72ef"),
                            BonusAgility = 37,
                            BonusFaith = 46,
                            BonusIntelligence = 33,
                            BonusStrength = 11,
                            CharacterId = new Guid("aa1646cf-6605-4a78-bc60-26a3011a71fe"),
                            Description = "Commodi nobis quia molestiae recusandae quis dolor.",
                            Name = "radiance"
                        });
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Characters.Character", b =>
                {
                    b.HasOne("WorldOfGamecraft.CharacterService.Domain.CharacterClasses.Class", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_classes_class_id");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Items.Item", b =>
                {
                    b.HasOne("WorldOfGamecraft.CharacterService.Domain.Characters.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.CharacterClasses.Class", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Characters.Character", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
