// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldOfGamecraft.CharacterService.Infrastructure;

#nullable disable

namespace WorldOfGamecraft.CharacterService.Infrastructure.Migrations
{
    [DbContext(typeof(CharactersDbContext))]
    [Migration("20240413101845_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.CharacterClasses.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_classes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_classes_name");

                    b.ToTable("classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("27847584-1797-484f-a31b-fc1011eebb09"),
                            Description = "Id dolorem recusandae commodi commodi voluptatibus totam.",
                            Name = "Warrior"
                        },
                        new
                        {
                            Id = new Guid("1309b85f-e0bc-4754-abd8-8b11e13b61ac"),
                            Description = "Cumque mollitia rerum necessitatibus quasi facere tempora.",
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = new Guid("53f96b8f-be67-4890-ac5b-f82867612726"),
                            Description = "Beatae omnis sint aspernatur quia ipsum deleniti ad magni.",
                            Name = "Mage"
                        },
                        new
                        {
                            Id = new Guid("ee252b1b-3539-48b2-b792-b8da3042839f"),
                            Description = "Dolore eos rerum vel dolorum soluta dolorem ea cum suscipit.",
                            Name = "Priest"
                        },
                        new
                        {
                            Id = new Guid("5332f2f4-5116-42eb-9d1a-c6b395ac3818"),
                            Description = "Vero eveniet alias ipsum qui et eveniet qui qui sapiente.",
                            Name = "Elf"
                        },
                        new
                        {
                            Id = new Guid("f0925ea0-3ac6-4458-8dce-aea903a23333"),
                            Description = "Nobis perferendis ea pariatur.",
                            Name = "Necromancer"
                        });
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BaseAgility")
                        .HasColumnType("integer")
                        .HasColumnName("base_agility");

                    b.Property<int>("BaseFaith")
                        .HasColumnType("integer")
                        .HasColumnName("base_faith");

                    b.Property<int>("BaseIntelligence")
                        .HasColumnType("integer")
                        .HasColumnName("base_intelligence");

                    b.Property<int>("BaseStrength")
                        .HasColumnType("integer")
                        .HasColumnName("base_strength");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<int>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_characters_class_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_name");

                    b.ToTable("characters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a388228-c79d-4194-bbea-c1d43e83559f"),
                            BaseAgility = 26,
                            BaseFaith = 17,
                            BaseIntelligence = 11,
                            BaseStrength = 17,
                            ClassId = new Guid("27847584-1797-484f-a31b-fc1011eebb09"),
                            Health = 1211,
                            Mana = 349,
                            Name = "DorisTheDynamic Factors Planner"
                        },
                        new
                        {
                            Id = new Guid("ae9c7d2e-1c09-4a66-9516-a15dc28f1a6e"),
                            BaseAgility = 33,
                            BaseFaith = 21,
                            BaseIntelligence = 42,
                            BaseStrength = 13,
                            ClassId = new Guid("5332f2f4-5116-42eb-9d1a-c6b395ac3818"),
                            Health = 810,
                            Mana = 251,
                            Name = "MoisesTheInternational Security Consultant"
                        },
                        new
                        {
                            Id = new Guid("1cabccc7-0242-4c8d-bd8e-b39c388be554"),
                            BaseAgility = 17,
                            BaseFaith = 31,
                            BaseIntelligence = 26,
                            BaseStrength = 29,
                            ClassId = new Guid("1309b85f-e0bc-4754-abd8-8b11e13b61ac"),
                            Health = 802,
                            Mana = 102,
                            Name = "KayleeTheCorporate Paradigm Coordinator"
                        },
                        new
                        {
                            Id = new Guid("00bd5ca7-efa2-4937-baae-232f5f5c4929"),
                            BaseAgility = 21,
                            BaseFaith = 43,
                            BaseIntelligence = 28,
                            BaseStrength = 21,
                            ClassId = new Guid("53f96b8f-be67-4890-ac5b-f82867612726"),
                            Health = 1118,
                            Mana = 336,
                            Name = "CarterTheNational Program Planner"
                        },
                        new
                        {
                            Id = new Guid("abac6546-b5dd-4722-bd15-edbd7582f58f"),
                            BaseAgility = 28,
                            BaseFaith = 24,
                            BaseIntelligence = 29,
                            BaseStrength = 24,
                            ClassId = new Guid("f0925ea0-3ac6-4458-8dce-aea903a23333"),
                            Health = 1160,
                            Mana = 171,
                            Name = "JeffTheChief Interactions Manager"
                        });
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Items.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BonusAgility")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_agility");

                    b.Property<int>("BonusFaith")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_faith");

                    b.Property<int>("BonusIntelligence")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_intelligence");

                    b.Property<int>("BonusStrength")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_strength");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_items_character_id");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ef4f863-23cc-444a-91cf-9ba65c54138a"),
                            BonusAgility = 31,
                            BonusFaith = 19,
                            BonusIntelligence = 29,
                            BonusStrength = 17,
                            CharacterId = new Guid("2a388228-c79d-4194-bbea-c1d43e83559f"),
                            Description = "Eum neque eaque expedita provident eaque.",
                            Name = "orchid"
                        },
                        new
                        {
                            Id = new Guid("e21235bc-261a-4780-b54e-0a774be5f5bb"),
                            BonusAgility = 14,
                            BonusFaith = 29,
                            BonusIntelligence = 50,
                            BonusStrength = 42,
                            CharacterId = new Guid("ae9c7d2e-1c09-4a66-9516-a15dc28f1a6e"),
                            Description = "Totam necessitatibus illo qui.",
                            Name = "monkey_king_bar"
                        },
                        new
                        {
                            Id = new Guid("9d7ea528-4e31-47f7-83d0-44bc93ae6727"),
                            BonusAgility = 11,
                            BonusFaith = 40,
                            BonusIntelligence = 21,
                            BonusStrength = 40,
                            CharacterId = new Guid("1cabccc7-0242-4c8d-bd8e-b39c388be554"),
                            Description = "Aliquid maiores voluptate minima dignissimos qui ut sit vel.",
                            Name = "dagon"
                        },
                        new
                        {
                            Id = new Guid("eecb8993-8477-4adb-893c-6b5fd1f1f69a"),
                            BonusAgility = 27,
                            BonusFaith = 39,
                            BonusIntelligence = 26,
                            BonusStrength = 23,
                            CharacterId = new Guid("00bd5ca7-efa2-4937-baae-232f5f5c4929"),
                            Description = "Molestiae ratione et odit necessitatibus accusantium.",
                            Name = "force_staff"
                        },
                        new
                        {
                            Id = new Guid("9f1482b0-2177-4adb-a536-65f5664fd99c"),
                            BonusAgility = 33,
                            BonusFaith = 37,
                            BonusIntelligence = 49,
                            BonusStrength = 31,
                            CharacterId = new Guid("abac6546-b5dd-4722-bd15-edbd7582f58f"),
                            Description = "Voluptatibus sapiente temporibus occaecati.",
                            Name = "black_king_bar"
                        });
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Characters.Character", b =>
                {
                    b.HasOne("WorldOfGamecraft.CharacterService.Domain.CharacterClasses.Class", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_classes_class_id");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Items.Item", b =>
                {
                    b.HasOne("WorldOfGamecraft.CharacterService.Domain.Characters.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_characters_character_id");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.CharacterClasses.Class", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WorldOfGamecraft.CharacterService.Domain.Characters.Character", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
